### ISSUE TITLE
Support for ESP-IDF 5.1

### ISSUE THREAD

**Issue by ivmarkov** [esp-rs/esp-idf-template#121]
@SergioGasquez Given that the upcoming `esp-idf-*` release actually does support ESP IDF 5.1, we should probably be having an option for that release as well?

**Comment by Vollbrecht** [comment]
my personal opinion:  maybe just update the 5.0 option -> use 5.1 instead and leave the two other options? as the template is mostly for generating new projects. This way we focus on support for v4.4 and the current v5 release branch.

**Comment by SergioGasquez** [comment]
@ivmarkov we discussed this topic in today's community meeting, and there was no hard opinion, but most of us agreed with removing `5.0` option and keeping only the `5.1` option for ESP-IDF 5, do you have any input on this?
