### ISSUE TITLE
Add support for new chips

### ISSUE THREAD

**Issue by SergioGasquez** [esp-rs/esp-idf-template#122]
Add support for new chips: esp32c2, esp32h2, esp32c6.

_Originally posted by @SergioGasquez in https://github.com/esp-rs/esp-idf-template/issues/121#issuecomment-1547416302_

**Comment by seanaye** [comment]
See #123 not sure if its that easy

**Comment by SergioGasquez** [comment]
Since not all chips support all the ESP-IDF versions we could:
- Update the default ESP-IDF version to `v5.0`
- If the user goes for non-default, update the list of ESP-IDF versions based on the chip to show only the supported version
