### ISSUE TITLE
How to configure esp-idf-template without cargo-generate

### ISSUE THREAD

**Issue by zdl361** [esp-rs/esp-idf-template#127]
Ubuntu 22.04.1 x86_64 GNU/Linux
I'm getting a segmentation fault when I running "cargo-generate generate esp-rs/esp-idf-template cargo" .
Both the cargo-generate binary installed by "cargo install cargo-generate" and  "cargo binstall cargo-generate" have segment fault and I can't fix it.
How to configure esp-idf-template without cargo-generate?

shell:

```bash
!32 ~/src % cargo generate esp-rs/esp-idf-template cargo         
⚠️   Favorite `esp-rs/esp-idf-template` not found in config, using it as a git repository: https://github.com/esp-rs/esp-idf-template.git
zsh: segmentation fault  cargo generate esp-rs/esp-idf-template cargo
```

GDB:
```
Core was generated by `/home/zdl361/.cargo/bin/cargo-generate generate esp-rs/esp-idf-template cargo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
```

**Comment by zdl361** [comment]
The bug comes from the code that handles git. The solution is to manually download the esp-idf-template to the local path. Use cargo generate to read templates from a local path
```bash
git clone https://github.com/esp-rs/esp-idf-template
cargo generate --vcs none ./esp-idf-template
```

**Comment by SergioGasquez** [comment]
Which version of cargo-generate are you using (`cargo generate --version`)?

**Comment by zdl361** [comment]
> Which version of cargo-generate are you using (`cargo generate --version`)?

cargo generate-generate 0.18.3

**Comment by SergioGasquez** [comment]
> cargo generate-generate 0.18.3

That's very weird, I'm using the same version but no issues, have you tried using the whole git url: `cargo generate https://github.com/esp-rs/esp-idf-template cargo`? And also, to test some other thing, can you try generating esp-template `cargo generate -a esp-rs/esp-template`

**Comment by SergioGasquez** [comment]
Hi @zdl361, have you tried any of the suggested solutions?

**Comment by zdl361** [comment]
![图片](https://github.com/esp-rs/esp-idf-template/assets/71546076/ff8370f2-b7a5-47a3-8191-3fbd45844713)
![图片](https://github.com/esp-rs/esp-idf-template/assets/71546076/8931dbe8-1f5c-4fb8-b1a9-a7c10edc7759)

**Comment by ivmarkov** [comment]
Closing as this is the only ever reported crash with `cargo-generate` and it is anyway an upstream problem.

Enhancing `esp-idf-template` to work also without `cargo-generate` is not an option, as an isolated crash on one developer machine with it is not enough of an evidence that we need to do such a big shift.
