### ISSUE TITLE
User facing template should releight on tagged esp-idf version

### ISSUE THREAD

**Issue by Vollbrecht** [esp-rs/esp-idf-template#144]
## Motivations

Every so often we got problems related to the fact that upstream esp-idf "release/x" versions introduces small breaking changes for us. Sometimes they are only breaking in Rust not in C, but sometimes also for both. The official documentations mentions that the "release/x" versions on github are in fact always seen as a beta release, and if we look back at the fully tagged versions they are the more stable versions ( Trying harder to not introduce breaking changes). 

I brought the topic up again in the last community meeting and Juraj ( who is a bit  involved in the release of esp-idf) and Scott both think its better if we relight on the tagged versions for anything that users directly interact with. I also think this should be the case. 

The direct drawback is that we have to update the template every new release to stay up to date, but i think a small version bump every 2-3 or so month is worth it, to not have users struggle with sudden breaking changes. I think for the master branches of hal/svc we still should use the "release/x" branches underlying, this change should be for the template only. 

What are your opinions @ivmarkov @SergioGasquez ?

**Comment by SergioGasquez** [comment]
I think it's a good change as it should be more stable, thanks for suggesting and implementing this!
