### ISSUE TITLE
Can use PSRAM?

### ISSUE THREAD

**Issue by xiaguangbo** [esp-rs/esp-idf-template#229]
esp32s3 have 8MB PSRAM, rust std `Vec` `String` can use PSRAM?

**Comment by ivmarkov** [comment]
Can you use [the Matrix `esp-rs` room](https://matrix.to/#/#esp-rs:matrix.org) for asking these questions?

**Comment by xiaguangbo** [comment]
@ivmarkov ok, i uknow Matrix at where, header page no see

**Comment by ivmarkov** [comment]
I just pasted you the link to the Matrix room. Just login there.
