### ISSUE TITLE
'esp32-s3' is not a recognized processor for this target

### ISSUE THREAD

**Issue by adrien3d** [esp-rs/esp-idf-template#230]
Not sure about where to post for my issue, as it seems related to `rustc-std-workspace-core`.
I started a project from the cargo generate with std, and, as I already have a functional esp32c6 project, I put the code and config to another one, targeting esp32s3.
Source of the new project is [here](https://github.com/adrien3d/rustdio)
But, when running `cargo build`, I have the following errors:
>   Compiling rustc-std-workspace-core v1.99.0 (/home/achapelet/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> error: data-layout for target `xtensa-esp32s3-espidf`, `e-m:e-p:32:32-v1:8:8-i64:64-i128:128-n32`, differs from LLVM target's `xtensa-none-elf` default layout, `e-m:e-p:32:32-i8:8:32-i16:16:32-i64:64-n32`
> 
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> error: could not compile `rustc-std-workspace-core` (lib) due to 1 previous error
> warning: build failed, waiting for other jobs to finish...
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> error: could not compile `core` (lib) due to 1 previous error
> error: could not compile `libc` (lib) due to 1 previous error
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> 'esp32-s3' is not a recognized processor for this target (ignoring processor)
> error: could not compile `compiler_builtins` (lib) due to 1 previous error

**Comment by SergioGasquez** [comment]
Looks like you are not using the `esp` toolchain to build the project. You need to install the Xtensa Rust with espup, see https://docs.esp-rs.org/book/installation/riscv-and-xtensa.html. And you can override the cargo command with `cargo +esp build...`. 

As for the CI, you can add the `+esp` on the cargo command or add the `override: true` in the [input of the toolchain](https://github.com/esp-rs/xtensa-toolchain/tree/v1.5/?tab=readme-ov-file#inputs).

Please, use the [Matrix channel for similar questions](https://matrix.to/#/#esp-rs:matrix.org).
