### ISSUE TITLE
why no_std and no_main

### ISSUE THREAD

**Issue by bestman8** [esp-rs/esp-idf-template#245]
when i tried this a few days ago it didn't have those changes so is there any reason why.
imo this is kinda confusing like can i just remove those or do things break when i remove them.

talking about these in main.rs
```rs
#![no_std]
#![no_main]

#[no_mangle]
```

**Comment by ivmarkov** [comment]
Thanks for noticing!
These were forgotten since the last change to the template that simplified it (who uses the template without STD?).

I've fixed it now.
