### ISSUE TITLE
Remove Rust toolchain question

### ISSUE THREAD

**Issue by SergioGasquez** [esp-rs/esp-idf-template#39]
I see no value in having [a question for the desired Rust toolchain](https://github.com/esp-rs/esp-idf-template/blob/37cfcf07029bab1807febb08af6bf39c55d368b4/cargo/cargo-generate.toml#L13-L16) when generating the project, we could do [like in esp-template](https://github.com/esp-rs/esp-template/blob/main/rust-toolchain.toml) and assume the toolchain based on the selected target (`nigthly` for `esp32c3`, `esp` otherwise)

**Comment by MabezDev** [comment]
That's a good point, seems like a good idea!
