### ISSUE TITLE
Assignment clash to rustflags with espidfver=mainline and mcu=esp32-c3

### ISSUE THREAD

**Issue by faulesocke** [esp-rs/esp-idf-template#66]
When combining these two options, in `.cargo/config.toml` the second `rustflags =` assignment in https://github.com/esp-rs/esp-idf-template/blob/master/cargo/.cargo/config.toml#L27 overrides the first assignment in line 7, causing it to be ignored. The issue can be fixed by adding the contents of the first assignment as two items to the list of the second assignment.

**Comment by ivmarkov** [comment]
Thanks for reporting! Fixed with https://github.com/esp-rs/esp-idf-template/commit/d7799f7539e7c2e4993a401dccbd898f06dba6ff
