### ISSUE TITLE
Add LLVM and CLang as prerequisites in README file

### ISSUE THREAD

**Issue by theguardian58** [esp-rs/esp-idf-template#70]
Installation of LLVM and Clang is required for successfully building the template. I recommend adding a reference to [this documentation](https://rust-lang.github.io/rust-bindgen/requirements.html#installing-clang) in the README file.

**Comment by ivmarkov** [comment]
The installation of Clang was already covered in the README, but I agree it was a bit unclear in wording. I've tried to tidy it up.

Installation of LLVM (whatever that means? like the extra LLVM tools or what?) is **not** necessary. LLVM (as in the compiler backend) is obviously part of the Rust and Clang compilers themselves.
