### ISSUE TITLE
Error connecting to ws://localhost:9012. Please reload the page.

### ISSUE THREAD

**Issue by wlopezob** [esp-rs/esp-idf-template#77]
Hi, when execute  **./scripts/run-wokwi.sh debug**  in devcontainer is result open the follow url: https://wokwi.com/_alpha/wembed/xxxxxxxx?partner=espressif&port=9012&data=demo but the page not work.

The error is: Error connecting to ws://localhost:9012. Please reload the page.

Please help me!.
![01](https://user-images.githubusercontent.com/16323429/212597360-8ac5b8f4-df2a-43e8-9ff5-fb7858c3a693.PNG)

Thank you.

**Comment by SergioGasquez** [comment]
Hi!
Just gave a quick try to simulate the default project template with both the dockerhub image (had to [install `wokwi-server`](https://github.com/MabezDev/wokwi-server#installation)) and building it from the Dockerfile, and had no issues. Could you elaborate on a few ends?
- Are you running the devcontainer using the dockerhub image or building it from the Dockerfile?
- What are you using as [`WOKWI_PROJECT_ID`](https://github.com/esp-rs/esp-idf-template/blob/master/cargo/scripts/run-wokwi.sh#L36)?
- Have you tried to simulate the template project with no changes?
- I assume you are using VsCode, can you check the `PORTS` tab of VsCode? 
![image](https://user-images.githubusercontent.com/12926049/212627929-b5d13ef8-0927-4648-bd36-a525017ea7d4.png)

**Comment by wlopezob** [comment]
Hi @SergioGasquez .

I was again run the project and it is ok.

Thank you.
