### ISSUE TITLE
Help with linker `xtensa-esp32-elf-gcc` not found

### ISSUE THREAD

**Issue by surendersampath** [esp-rs/esp-idf-template#78]
![image](https://user-images.githubusercontent.com/44113702/213939281-4a8e0d70-aea1-4ee1-99d6-67d9943a47a8.png)

I'm having issues with xxtensa linker.

I used cargo generate to generate esp no std template and then executed cargo build.
Could anyone help pleasE?

**Comment by MabezDev** [comment]
You need to install the linker manually from https://github.com/espressif/crosstool-NG/releases, or let [espup](https://esp-rs.github.io/book/installation/installation.html#espup) do it for you.
