### ISSUE TITLE
Pointing to right githib repo in README.md

### ISSUE THREAD

**Issue by mikkeldamsgaard** [esp-rs/esp-idf-template#8]
Currently the example to run the generate is pointing to the ivmarkov repo.
cargo generate --vcs none --git https://github.com/ivmarkov/esp-idf-template cargo

It would be a good idea to change that tho
cargo generate --vcs none --git https://github.com/ivmarkov/esp-idf-template cargo

**Comment by ivmarkov** [comment]
Thanks for spotting that. Old repo still works (redirects to the new one), yet indeed a good idea to fix. 

Fixed as part of https://github.com/esp-rs/esp-idf-template/commit/ead106c079a5d456628e7efd290b427ac2f3c8e1.
